### ISSUE TITLE
Issue installing on Intel Mac in Blender 4.0.2

### ISSUE THREAD

**Issue by levybergman** [EatTheFuture/camera_projector#5]
Gents,

I get the following message on Intel Mac in Blender 4.0.2 and impossible to activate the add-on which works perfectly fine in 3.6.7

Traceback (most recent call last):
  File "/Applications/Blender 4.app/Contents/Resources/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "/Applications/Blender 4.app/Contents/Resources/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'camera_projector-0'

Thanks for your help in advance!

**Comment by Leonobu** [comment]
Same problem for me

**Comment by Leonobu** [comment]
Click on code green button, and then download ZIP. This file will work for you

**Comment by levybergman** [comment]
thanks a lot!!

> Click on code green button, and then download ZIP. This file will work for you
