### ISSUE TITLE
4.2.1 support

### ISSUE THREAD

**Issue by loicbramoulle** [EatTheFuture/camera_projector#7]
Hi, I think 4.2 isn't supported yet ? we have this error when trying to enable the addon:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\addon_utils.py", line 407, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'camera_projector-0'

and a slightly different one when trying to instal it:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1326, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2386, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2514, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\startup\bl_operators\userpref.py", line 821, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'camera_projector-0'

**Comment by loicbramoulle** [comment]
Ow ! so downloading and installing the Master works (green button), but the latest release .zip does not ?

Amazing in any case, I've beeing doing cammap heavily since 2008 in Maya, it was just this single node, and since 6 years in blender I've only been using the modifier, which works but is indeed a wacky method compared to this mapping one like in Maya !

**Comment by cessen** [comment]
Thanks for the report!

I'm not sure what to make of that error.  It's complaining about a missing `camera_projector-0` module, but there's never been any such module in any release of Camera Shakify.  My best guess is that you accidentally installed it in a weird way...?  But I'm really not sure.

If you can repro the issue that would be really appreciated, if for no other reason than to satisfy my curiosity.  But if not, no worries, since you at least have it working now.

(That also reminded me that the listed releases are pretty old, and people shouldn't really be using them, so I've removed them.  Indeed, everyone should just be downloading latest master at this point.  Although what I really should do is put it up on Blender's new extensions platform.)

**Comment by cessen** [comment]
Oh geeze, brain fart.  For some reason I thought this was the Camera Shakify repo.  That's what I get for responding to bug reports early in the morning.

Actually, this whole repo should probably be locked with a message at this point.  The Camera Project node is actually part of [Compify](https://github.com/EatTheFuture/compify), and we only had it split off into its own addon while we weren't yet ready to release Compify itself.  Since Compify is now released, this addon deprecated and this repo doesn't receive any updates or bug fixes.  You should be using Compify instead.

**Comment by loicbramoulle** [comment]
oh right I saw Ian demo Compify on the Patreon, groundbreaking stuff, thanks heaps !
